import type { SuspectProfile, EvidenceType, LabTest, Scenario, StoryCard, CrimeSceneTile } from '@/types';

export const SUSPECT_PROFILES: SuspectProfile[] = [
  {
    id: 'S-001',
    name: 'Margaret Voss',
    age: 51,
    occupation: 'Former Art Dealer',
    education: 'MFA Fine Arts Columbia University',
    psychologicalProfile: ['Suffers from chronic insomnia and anxiety', 'History of prescription sleep medication use (Ambien)', 'Highly detail-oriented and organized', 'Struggles with emotional expression', 'Financial stress from declining art market'],
    background: 'Grew up in affluent Connecticut family. Built successful art gallery in Manhattan during the 1990s. Sold gallery in 2015 following market downturn. Known in social circles as reserved and private. No criminal record. Has history of contentious business relationships.',
  },
  {
    id: 'S-002',
    name: 'David Chen',
    age: 34,
    occupation: 'Software Engineer',
    education: 'BS Computer Science MIT',
    psychologicalProfile: ['Highly intelligent but socially awkward', 'History of gambling addiction (in recovery)', 'Struggles with authority figures', 'Tendency toward obsessive behavior', 'Financial instability from past debts'],
    background: 'Raised in San Francisco by immigrant parents. Dropped out of PhD program at Stanford. Worked at several tech startups. Filed for bankruptcy 3 years ago due to gambling debts. Currently employed at mid-tier software company. Known for being brilliant but difficult to work with.',
  },
  {
    id: 'S-003',
    name: 'Jane Morrison',
    age: 38,
    occupation: 'Real Estate Agent',
    education: 'BA Business Administration State University',
    psychologicalProfile: ['Type-A personality, highly competitive', 'Difficulty maintaining long-term relationships', 'Financial stress from recent divorce', 'Tendency to bend rules to close deals', 'History of prescription anxiety medication use'],
    background: 'Grew up in small-town Iowa. Moved to city 15 years ago. Built moderately successful real estate career. Divorced 2 years ago after contentious proceedings. Known in professional circles as aggressive and ambitious. No criminal record but multiple client complaints on file.',
  },
  {
    id: 'S-004',
    name: 'Leonard Holt',
    age: 52,
    occupation: 'Business Executive',
    education: 'MBA Harvard Business School',
    psychologicalProfile: ['Charismatic but manipulative', 'History of extramarital affairs', 'Financial pressure from lifestyle inflation', 'Risk-taking behavior in business dealings', 'Defensive when questioned about finances'],
    background: 'Son of wealthy industrialist. Took over family business in late 30s. Expanded operations aggressively with leveraged buyouts. Lives beyond means (yacht, country club memberships, expensive cars). Recently faced liquidity issues. Known for charming public persona masking ruthless business tactics.',
  },
  {
    id: 'S-005',
    name: 'Sarah Delgado',
    age: 29,
    occupation: 'Housekeeper',
    education: 'High School Diploma',
    psychologicalProfile: ['Observant and detail-oriented', 'Struggles with boundary setting', 'Financial stress supporting extended family', 'Loyal but easily taken advantage of', 'History of unreported workplace issues'],
    background: 'Immigrant from El Salvador, arrived at age 12. Works two jobs to support family. Employed in domestic service for 8 years. Known for being reliable and discreet. Has worked for multiple wealthy families. No criminal record. Often witnesses but doesn\'t report household conflicts.',
  },
  {
    id: 'S-006',
    name: 'Marcus Delaney',
    age: 47,
    occupation: 'Insurance Adjuster',
    education: 'BS Business Administration',
    psychologicalProfile: ['Quietly suspicious of others', 'Obsessive attention to detail', 'History of mild paranoia', 'Tends to document everything compulsively'],
    background: 'Moved into the neighborhood three years ago following a difficult divorce. Keeps odd hours and has been observed photographing nearby properties, which he claims is work-related. No criminal record but was named in a civil suit that was later dropped. Colleagues describe him as competent but socially withdrawn.',
  },
  {
    id: 'S-007',
    name: 'Diane Mercer',
    age: 52,
    occupation: 'Real Estate Agent',
    education: 'BA Communications',
    psychologicalProfile: ['Narcissistic tendencies', 'Sharp temper behind polished exterior', 'Highly controlling in personal relationships', 'Preoccupied with public image'],
    background: 'Built her career on knowing everyone\'s business in the community. Maintains a careful public persona but close friends report volatile behavior behind closed doors. Recently updated her will and insurance policies, describing it as routine. Known for leveraging personal connections to close deals.',
  },
  {
    id: 'S-008',
    name: 'Colin Ashworth',
    age: 29,
    occupation: 'Graduate Student',
    education: 'MA History (in progress)',
    psychologicalProfile: ['Intellectually gifted but emotionally withdrawn', 'Feelings of inadequacy compared to family', 'Tendency to brood and isolate', 'Guards personal writings obsessively'],
    background: 'Has always felt overlooked in favor of more successful family members. Keeps a personal journal that he guards closely. Recently returned from a six-month research trip abroad with gaps in his timeline that are difficult to verify. Known among peers as brilliant but brooding.',
  },
  {
    id: 'S-009',
    name: 'Ruth Nakamura',
    age: 62,
    occupation: 'Retired Schoolteacher',
    education: 'MEd Education',
    psychologicalProfile: ['Fiercely protective of loved ones', 'Controlling behavior masked as concern', 'Strong moral convictions', 'Difficulty accepting change'],
    background: 'Spent 35 years teaching elementary school before retiring. Sharp-minded and opinionated about everyone in her family\'s lives. Neighbors describe her as warm but overbearing. Made a significant unexplained bank withdrawal recently. Known for keeping meticulous personal records.',
  },
  {
    id: 'S-010',
    name: 'Tyler Okonkwo',
    age: 24,
    occupation: 'Warehouse Associate',
    education: 'High School Diploma',
    psychologicalProfile: ['Uses humor to deflect serious situations', 'History of financial irresponsibility', 'Avoidant attachment style', 'Impulsive decision-making'],
    background: 'Easygoing on the surface but has a history of borrowing money from family without repaying. Recently quit a second job without explanation and has been spending more time than usual around the family home. Tends to laugh off serious questions. No criminal record but known for unreliability.',
  },
  {
    id: 'S-011',
    name: 'Sandra Whitfield',
    age: 44,
    occupation: 'Dental Hygienist',
    education: 'AS Dental Hygiene',
    psychologicalProfile: ['Difficulty moving on from past relationships', 'Borderline obsessive monitoring behavior', 'Deep-seated fear of abandonment', 'History of anxiety and depression'],
    background: 'Ended a long relationship abruptly and has not fully moved on. Occasionally drives past her former partner\'s residence and has sent several unanswered messages in recent months. Describes her interest as concern. Has no history of violence but has a restraining order on file from a prior relationship.',
  },
  {
    id: 'S-012',
    name: 'Eliot Farrow',
    age: 61,
    occupation: 'Retired Military Officer',
    education: 'BS Military Science West Point',
    psychologicalProfile: ['Authoritarian personality', 'PTSD from combat service', 'Difficulty expressing vulnerability', 'Prone to veiled threats when agitated'],
    background: 'Served 30 years in the Army before retiring as a Colonel. Ran a strict household and expects obedience from everyone around him. Has a strained relationship with at least one of his children. Owns several legally registered firearms. Neighbors describe him as disciplined but intimidating.',
  },
  {
    id: 'S-013',
    name: 'Priya Subramanian',
    age: 38,
    occupation: 'Pediatric Nurse',
    education: 'BSN Nursing',
    psychologicalProfile: ['Calm under pressure but internally stressed', 'Secretive about personal life', 'History of enabling behavior in relationships', 'Knowledge of pharmaceuticals and dosages'],
    background: 'Well-liked by coworkers and known for handling emergencies with composure. Admits her marriage has been strained for years. Has access to medical supplies and pharmaceutical knowledge through her work. Close friends say she has been \'planning something\' but won\'t elaborate. Maintains a private demeanor.',
  },
  {
    id: 'S-014',
    name: 'Gwen Calloway',
    age: 33,
    occupation: 'Florist',
    education: 'Certificate in Floral Design',
    psychologicalProfile: ['People-pleaser who avoids conflict', 'Suppresses anger until it erupts', 'Financial anxiety from small business ownership', 'Trust issues stemming from family disputes'],
    background: 'Runs a small flower shop in the downtown area and is known as the family peacemaker. Recently had a falling-out with a close relative over money and has been absent from family gatherings since. Her shop was broken into last month but she declined to file a full police report. Outwardly cheerful but privately troubled.',
  },
  {
    id: 'S-015',
    name: 'Nolan Breslin',
    age: 22,
    occupation: 'College Student',
    education: 'Pursuing BA (Undeclared)',
    psychologicalProfile: ['Socially withdrawn and secretive', 'Struggles with identity and direction', 'Susceptible to peer influence', 'Difficulty maintaining eye contact during questioning'],
    background: 'Dropped his engineering major and has been spending time with a new social circle that family members know little about. Has given inconsistent accounts of his whereabouts on certain evenings. Known among roommates as quiet and private. No criminal record but campus security has noted him near restricted areas.',
  },
  {
    id: 'S-016',
    name: 'Margaret Tran',
    age: 56,
    occupation: 'Bookkeeper',
    education: 'AS Accounting',
    psychologicalProfile: ['Obsessively detail-oriented', 'Compulsive record-keeping behavior', 'Distrust of authority figures', 'Anxiety about being overlooked or dismissed'],
    background: 'Meticulous professional who notices discrepancies others miss. Recently discovered what she believes is a financial irregularity in a family account but hasn\'t decided who to tell. Neighbors describe her as the type who keeps records of everything. Carries a folder of printed emails in her purse at all times.',
  },
  {
    id: 'S-017',
    name: 'Jerome Hutchins',
    age: 41,
    occupation: 'High School Football Coach',
    education: 'BS Physical Education',
    psychologicalProfile: ['Outwardly gregarious but privately volatile', 'History of anger management issues', 'Tendency to control narratives', 'Complicated romantic history'],
    background: 'Well-liked in the community and volunteers as a youth mentor. Has a complicated personal history that includes at least one contested restraining order. Quick to offer his own version of events before being asked. Was seen having a heated argument with an unknown individual near his vehicle recently.',
  },
  {
    id: 'S-018',
    name: 'Lena Kowalski',
    age: 45,
    occupation: 'Office Manager',
    education: 'BA Business Administration',
    psychologicalProfile: ['Territorial about her professional role', 'Passive-aggressive communication style', 'Resentment from being passed over for promotion', 'Tendency to leverage information for power'],
    background: 'Efficient administrator who controls access to most of her company\'s files. Recently learned she was passed over for a promotion and was overheard saying she knew things that could blow everything open. Has taken several unplanned personal days in the past month. Colleagues find her competent but unsettling.',
  },
  {
    id: 'S-019',
    name: 'Desmond Achebe',
    age: 50,
    occupation: 'Senior Accountant',
    education: 'BS Accounting CPA',
    psychologicalProfile: ['Reserved and precise to a fault', 'Heightened anxiety in recent months', 'Strong sense of professional ethics', 'Conflicted between loyalty and duty'],
    background: 'Has worked with the same firm for twenty years and prides himself on discretion. Recently flagged an internal financial discrepancy and was told to stay quiet about it. Has complied so far but has kept his own documentation. Colleagues say he seems unusually anxious lately.',
  },
  {
    id: 'S-020',
    name: 'Cassandra Voss',
    age: 36,
    occupation: 'Marketing Director',
    education: 'MBA Marketing',
    psychologicalProfile: ['Ambitious and strategically manipulative', 'Thrives on building alliances', 'Competitive to the point of ruthlessness', 'Difficulty accepting blame'],
    background: 'Known for building professional alliances and knowing when to call in favors. Recently had a public disagreement with a senior colleague that HR got involved in. Claims all interactions were routine. Has rapidly climbed the corporate ladder and made enemies along the way.',
  },
  {
    id: 'S-021',
    name: 'Ray Espinoza',
    age: 53,
    occupation: 'Construction Foreman',
    education: 'Trade Certification',
    psychologicalProfile: ['Blunt and confrontational when challenged', 'History of cutting corners', 'Paranoid about anonymous complaints', 'Difficulty trusting subordinates'],
    background: 'Worked in construction for over 30 years and is used to being in charge. Has a reputation for cutting corners on job sites. An anonymous complaint was recently filed against him, and he claims to know exactly who filed it. Has access to keys and security codes at multiple work sites.',
  },
  {
    id: 'S-022',
    name: 'Felicity Drummond',
    age: 29,
    occupation: 'Junior Paralegal',
    education: 'BA Political Science Paralegal Certificate',
    psychologicalProfile: ['Eager to prove herself', 'Hypervigilant about personal safety', 'Anxiety from witnessing workplace misconduct', 'Trust issues after confiding in wrong person'],
    background: 'Has been quietly building a file on workplace misconduct she witnessed months ago. Confided in one colleague who she now suspects may have told the wrong person. Has since changed her passwords, her route home from work, and stopped taking lunch in the break room. Driven but increasingly isolated.',
  },
  {
    id: 'S-023',
    name: 'Arthur Kimani',
    age: 60,
    occupation: 'CEO',
    education: 'MBA Wharton School of Business',
    psychologicalProfile: ['Charming and difficult to read', 'History of manipulating business situations', 'Maintains private security detail', 'Comfortable with deception'],
    background: 'Has negotiated his way out of difficult situations for decades. Recently tried to buy out a business partner under unusual terms and was refused. Known to have a private security detail on call, though he downplays the reason. His calendar entries around key dates have been deleted.',
  },
  {
    id: 'S-024',
    name: 'Monica Graves',
    age: 34,
    occupation: 'Pharmacist',
    education: 'PharmD',
    psychologicalProfile: ['Methodical and private', 'Unusual curiosity about toxicology', 'Perfectionist tendencies', 'Emotionally detached in professional settings'],
    background: 'Has access to a wide range of controlled substances and keeps immaculate dispensing records except for an unexplained three-day gap she attributes to a software glitch. Recently asked a colleague oddly specific questions about overdose thresholds. Coworkers describe her as private but not suspicious until recently.',
  },
  {
    id: 'S-025',
    name: 'Steven Park',
    age: 42,
    occupation: 'IT Security Analyst',
    education: 'BS Computer Science',
    psychologicalProfile: ['Socially awkward but highly perceptive', 'Paranoid about digital surveillance', 'Tendency to hoard information', 'Difficulty reporting through official channels'],
    background: 'Has administrative access to most of his company\'s communications infrastructure. Recently discovered something in a server log that he hasn\'t reported, claiming he needs more time to be sure. Made a copy of the log and stored it off-site. Has been very careful about who he talks to.',
  },
  {
    id: 'S-026',
    name: 'Harriet Osei',
    age: 48,
    occupation: 'Human Resources Director',
    education: 'MA Organizational Psychology',
    psychologicalProfile: ['Politically savvy and unflappable', 'Uses knowledge as leverage', 'Skilled at managing secrets', 'Boundary issues between professional and personal'],
    background: 'Has managed more sensitive personnel situations than most people know about. Recently brokered a private settlement between two employees and made sure the files were sealed. Has a reputation for knowing exactly what skeletons are in which closets and using that knowledge carefully.',
  },
  {
    id: 'S-027',
    name: 'Danny Ruiz',
    age: 27,
    occupation: 'Delivery Driver',
    education: 'Some College',
    psychologicalProfile: ['Friendly but deceptive when pressured', 'Impulsive behavior patterns', 'Tendency to access restricted areas', 'Gives inconsistent accounts under stress'],
    background: 'Was hired on a short-term contract and spent considerable time in areas most temporary staff never access. Left his position suddenly without explanation and forgot to return his security badge. When contacted by investigators, seemed nervous and gave two different versions of his last day at work.',
  },
  {
    id: 'S-028',
    name: 'Vivian St. Claire',
    age: 63,
    occupation: 'Retired Judge',
    education: 'JD Yale Law School',
    psychologicalProfile: ['Imposing and judgmental', 'Compulsive need to observe and document', 'Strong opinions she withholds strategically', 'History of insomnia and nighttime vigilance'],
    background: 'Has lived in the same neighborhood for thirty years and misses nothing. Keeps a handwritten log of unusual activity on her street. Has strong opinions about certain individuals that she says are not for public record. Spent 25 years on the bench before retiring. Known for sharp legal mind and uncompromising standards.',
  },
  {
    id: 'S-029',
    name: 'Tobias Wegner',
    age: 39,
    occupation: 'Personal Trainer',
    education: 'BS Kinesiology',
    psychologicalProfile: ['Sociable but guarded about personal life', 'Physically imposing and aware of it', 'History of unresolved interpersonal conflicts', 'Tends to minimize serious situations'],
    background: 'Has a wide circle of acquaintances and knows how to read people. Had a falling-out with a close friend roughly six months ago over something neither will fully explain. Was at the gym the evening of a recent incident and has clients who can partially confirm his whereabouts but not for the full window of time.',
  },
  {
    id: 'S-030',
    name: 'Adaeze Nwosu',
    age: 31,
    occupation: 'Social Worker',
    education: 'MSW Social Work',
    psychologicalProfile: ['Empathetic to a fault', 'Difficulty separating professional and personal involvement', 'Strong sense of justice', 'Prone to overstepping professional boundaries'],
    background: 'Well-connected to community resources and has ongoing contact with multiple families in a professional capacity. Recently escalated a concern about a household to her supervisor and was told the case didn\'t meet the threshold for intervention. Disagreed strongly and documented her objection. Known for blurring the line between casework and personal involvement.',
  },
  {
    id: 'S-031',
    name: 'Gary Thornton',
    age: 55,
    occupation: 'Landscaper',
    education: 'High School Diploma',
    psychologicalProfile: ['Gruff exterior masking loneliness', 'Territorial about property boundaries', 'Observant but reluctant to share information', 'History of mild alcohol abuse'],
    background: 'Has lived in the same neighborhood for twelve years and seen more than he lets on. Has a habit of lingering near property lines and once had a formal dispute with a neighbor over access. His truck was spotted in an unusual location recently. When asked, he said he was just driving around. Works alone most days.',
  },
  {
    id: 'S-032',
    name: 'Serena Holt',
    age: 22,
    occupation: 'Barista',
    education: 'Pursuing BA English Literature',
    psychologicalProfile: ['Perceptive beyond her years', 'Indecisive about taking action', 'Anxiety about getting involved in others\' problems', 'Tendency to overthink situations'],
    background: 'Works part-time at a local coffee shop while attending college. Has served regular customers on multiple occasions and picks up on subtle behavioral changes. Confided in a coworker about something a customer said that she found alarming but didn\'t follow up on. Has been trying to piece together a timeline on her own.',
  },
  {
    id: 'S-033',
    name: 'Thomas Gallagher',
    age: 65,
    occupation: 'Priest',
    education: 'MDiv Theology',
    psychologicalProfile: ['Calm and trusted but internally conflicted', 'Struggles between confidentiality and moral duty', 'History of depression', 'Carries emotional burdens of others'],
    background: 'Well-trusted in the local community and has served as parish priest for over 20 years. Has heard things in confidence that may be relevant to various situations but struggles with the tension between duty and discretion. Known for private meetings that he declines to confirm or deny. Deeply principled but visibly burdened.',
  },
  {
    id: 'S-034',
    name: 'Rosario Delgado',
    age: 44,
    occupation: 'Elementary School Teacher',
    education: 'MEd Elementary Education',
    psychologicalProfile: ['Devoted to her students and community', 'Prone to emotional distress when concerns are dismissed', 'Strong maternal instinct', 'Difficulty letting go of unresolved situations'],
    background: 'Respected in the community with a wide network of relationships with local families. Has a keen eye for noticing concerning changes in behavior among students and families. Known for trying to flag issues through proper channels even when dismissed. Cooperative with authorities but visibly distressed by injustice.',
  },
  {
    id: 'S-035',
    name: 'Brian Cho',
    age: 37,
    occupation: 'Youth Soccer Coach',
    education: 'BS Physical Education',
    psychologicalProfile: ['High-energy and outwardly likable', 'Tendency to overstep personal boundaries', 'Defensive when confronted', 'History of heated public arguments'],
    background: 'Well-liked by students and has access to after-school facilities. Knows the routines of dozens of local families through his coaching work. Recently had a public argument with a parent at a tournament about something other than sports. Known for his enthusiasm but also for his short temper when challenged.',
  },
  {
    id: 'S-036',
    name: 'Pauline Rhodes',
    age: 64,
    occupation: 'Retired Librarian',
    education: 'MLS Library Science',
    psychologicalProfile: ['Kind but secretly burdened by knowledge', 'Compulsive collector of information', 'Cryptic communication style', 'Fear of confrontation'],
    background: 'Has known many families in the community for decades and is trusted by everyone, perhaps too much. Recently found something unexpected among donated materials that she hasn\'t told anyone about. Made a cryptic comment to a neighbor about things coming to light and has since become noticeably quiet. Known for her gentle demeanor.',
  },
  {
    id: 'S-037',
    name: 'Kwame Asante',
    age: 46,
    occupation: 'Jazz Musician',
    education: 'BFA Music Performance',
    psychologicalProfile: ['Charismatic and evasive', 'Avoids commitment and fixed schedules', 'Carries emotional weight he won\'t discuss', 'History of substance use in younger years'],
    background: 'Moves between social circles with ease and rarely commits to a fixed schedule. Friends say he is carrying something but won\'t say what. Known for his talent and charm but also for deflecting personal questions. Has performed at venues across the city for over two decades. Unconventional lifestyle makes his whereabouts hard to pin down.',
  },
  {
    id: 'S-038',
    name: 'Dr. Ingrid Paulos',
    age: 49,
    occupation: 'General Practitioner',
    education: 'MD Johns Hopkins University',
    psychologicalProfile: ['Professionally guarded', 'Conflicted about patient confidentiality', 'Methodical and cautious in all interactions', 'Increasing moral distress over ethical dilemmas'],
    background: 'Has served as a physician in the community for over 20 years and is aware of medical histories that could be relevant to various situations. Bound by confidentiality but has indicated that some things shouldn\'t stay private forever. Patient files show patterns she finds concerning. Known for her thoroughness and discretion.',
  },
  {
    id: 'S-039',
    name: 'Victor Lennox',
    age: 54,
    occupation: 'Criminal Defense Attorney',
    education: 'JD Georgetown Law',
    psychologicalProfile: ['Strategically cautious and composed', 'Comfortable with moral ambiguity', 'Selective about what he volunteers', 'History of representing controversial clients'],
    background: 'Has represented clients in sensitive cases for over two decades. Known for off-the-record conversations that he refuses to characterize. Has not invoked privilege but has been very selective about what he shares. His billing records show significant cash payments with no client names attached. Respected and feared in legal circles.',
  },
  {
    id: 'S-040',
    name: 'Dale Marsh',
    age: 36,
    occupation: 'Police Officer',
    education: 'BS Criminal Justice',
    psychologicalProfile: ['Overly cautious about making decisions', 'Tendency to delay under pressure', 'Defensive about procedural choices', 'Struggles with chain-of-command conflicts'],
    background: 'Competent and by-the-book on paper but has a reputation among colleagues for being overly cautious. Has been a patrol officer for 12 years without seeking promotion. Known for making judgment calls that are later questioned. Sometimes submits reports later than standard procedure requires. Claims he prefers to wait for guidance.',
  },
  {
    id: 'S-041',
    name: 'Claire Sutton',
    age: 41,
    occupation: 'Licensed Therapist',
    education: 'MSW LCSW',
    psychologicalProfile: ['Measured and professionally composed', 'Carries the emotional weight of her clients', 'Conflicted about boundaries of confidentiality', 'History of burnout and compassion fatigue'],
    background: 'Has had therapeutic relationships with multiple individuals in the community. Shares limited information citing confidentiality but has hinted at concerns that fall outside the scope of privilege. Known for last-minute appointment cancellations by unknown clients. Respected by peers but visibly strained in recent months.',
  },
  {
    id: 'S-042',
    name: 'Hector Malone',
    age: 58,
    occupation: 'Financial Advisor',
    education: 'BS Finance CFP',
    psychologicalProfile: ['Meticulous about appearance and reputation', 'History of bending fiduciary rules', 'Defensive when accounts are scrutinized', 'Anxiety about professional licensing'],
    background: 'Has managed significant assets for clients over a 30-year career. Recently restructured an estate plan under unusual time pressure and processed a large transfer he describes as routine portfolio rebalancing. Several accounts he managed have been frozen. Has hired his own attorney. Well-dressed and always composed in public.',
  },
  {
    id: 'S-043',
    name: 'Tamara Singh',
    age: 32,
    occupation: 'Paramedic',
    education: 'AS Emergency Medical Services',
    psychologicalProfile: ['Steady under pressure but frustrated by bureaucracy', 'Compulsive note-taker', 'Tendency to bypass official channels', 'History of clashing with supervisors'],
    background: 'Trained to notice things others miss and keeps a detailed personal log of observations from scenes. Has tried multiple times to amend official reports and been told case files are closed. Known for contacting journalists before investigators, which has complicated her credibility. Passionate about her work but increasingly disillusioned.',
  },
  {
    id: 'S-044',
    name: 'Gil Hartley',
    age: 43,
    occupation: 'Bartender',
    education: 'Some College',
    psychologicalProfile: ['Observant and discreet by nature', 'Reluctant to get involved in others\' affairs', 'Mild cynicism from years of late-night work', 'History of avoiding authority figures'],
    background: 'Has worked the late shift at various bars for over 20 years and has seen things at closing time that most people would find hard to believe. Observes behavioral changes in regular patrons and remembers conversations clearly but is reluctant to repeat them. Known for keeping to himself and minding his own business.',
  },
  {
    id: 'S-045',
    name: 'Carmen Flores',
    age: 35,
    occupation: 'Hotel Front Desk Clerk',
    education: 'AS Hospitality Management',
    psychologicalProfile: ['Efficient and trained to be unobtrusive', 'Excellent memory for faces and details', 'Conflict-avoidant in workplace settings', 'Tendency to notice but not report discrepancies'],
    background: 'Has worked in hospitality for 15 years across multiple hotels. Trained to be discreet and handle guest concerns without escalation. Has noticed discrepancies in guest bookings including names that don\'t match IDs presented. Mentions concerns to coworkers but not to management. Known for professionalism and reliability.',
  },
  {
    id: 'S-046',
    name: 'Pete Hargrove',
    age: 50,
    occupation: 'Handyman',
    education: 'Trade Certification',
    psychologicalProfile: ['Reliable but largely invisible to clients', 'Observant about changes in household routines', 'Non-confrontational to a fault', 'Mild resentment about being overlooked'],
    background: 'Has had access to numerous properties over a 25-year career in general contracting and repairs. Reliable and largely invisible to most households he works in. Has noticed unusual things during visits to properties but typically mentions them only to homeowners who often don\'t acknowledge the conversation. Lives alone and keeps to himself.',
  },
  {
    id: 'S-047',
    name: 'Yuki Tanaka',
    age: 26,
    occupation: 'Ride-share Driver',
    education: 'BA Sociology',
    psychologicalProfile: ['Attentive and cautious', 'Detailed recollection of events', 'Anxiety about personal safety', 'Tendency to save records compulsively'],
    background: 'Drives for multiple ride-share platforms and has a detailed recollection of routes, conversations, and drop-off locations. Saves trip logs meticulously. Has driven passengers to destinations that don\'t match stated locations. Waiting to be contacted by investigators rather than volunteering information. College-educated but struggling to find work in his field.',
  },
  {
    id: 'S-048',
    name: 'Rafe Dunning',
    age: 38,
    occupation: 'Unemployed',
    education: 'Unknown',
    psychologicalProfile: ['Evasive about personal history', 'Comfortable with deception', 'No fixed routine or attachments', 'History of using aliases'],
    background: 'Arrived in town approximately eight weeks ago and has given inconsistent answers about where he came from and why. Has been seen at multiple locations around town at different times, which he attributes to coincidence. Has no fixed address but isn\'t homeless in appearance. No criminal record under his current name.',
  },
  {
    id: 'S-049',
    name: 'Celeste Vane',
    age: 27,
    occupation: 'Freelance Photographer',
    education: 'BFA Photography',
    psychologicalProfile: ['Artistic and difficult to read', 'Boundary issues around consent and observation', 'Compulsive need to document surroundings', 'Socially detached'],
    background: 'Has been photographing the neighborhood for what she says is a personal project. Several of her photos recovered from a deleted social media account include individuals she claims not to know. Hard to pin down on specifics about her work or personal life. No criminal record but has received complaints about photographing private property.',
  },
  {
    id: 'S-050',
    name: 'Nadia Volkov',
    age: 44,
    occupation: 'Former Intelligence Analyst',
    education: 'MS International Relations Georgetown University',
    psychologicalProfile: ['Unnervingly calm under questioning', 'Deep understanding of surveillance and evidence handling', 'Secretive about past employment', 'Difficulty forming personal connections'],
    background: 'Relocated to the area under circumstances she describes as personal. Her former employer cannot be reached for comment. Has a clear understanding of surveillance, evidence handling, and investigative procedure that she attributes to professional habits. Volunteered to assist investigators and was politely declined. Precise and composed at all times.',
  },
];

export const EVIDENCE_TYPES: EvidenceType[] = [
  {
    id: 'weapon',
    category: 'Weapon',
    physicalCardNumber: 'E-001',
    canBeTestedWith: ['dna_test'],
  },
  {
    id: 'fiber',
    category: 'Trace Evidence',
    physicalCardNumber: 'E-002',
    canBeTestedWith: ['fiber_analysis'],
  },
  {
    id: 'phone_records',
    category: 'Digital Records',
    physicalCardNumber: 'E-003',
    canBeTestedWith: ['gps_triangulation'],
  },
  {
    id: 'financial_docs',
    category: 'Financial Documents',
    physicalCardNumber: 'E-004',
    canBeTestedWith: ['financial_audit'],
  },
  {
    id: 'security_footage',
    category: 'Surveillance',
    physicalCardNumber: 'E-005',
    canBeTestedWith: ['footage_enhancement'],
  },
];

export const STORY_CARDS: StoryCard[] = [
  {
    id: 'SC-001',
    physicalCardNumber: 'STORY-01',
    title: 'Hidden Affair',
    description: 'The victim was involved in a secret romantic relationship. This person had both motive and opportunity to silence the victim before the affair was exposed.',
    clueTypes: ['digital_device', 'handwritten_note', 'financial_records'],
  },
  {
    id: 'SC-002',
    physicalCardNumber: 'STORY-02',
    title: 'Insurance Fraud',
    description: 'A recently updated life insurance policy creates a powerful financial motive. The beneficiary stands to gain significantly from the victim\'s death.',
    clueTypes: ['legal_documents', 'financial_records'],
  },
  {
    id: 'SC-003',
    physicalCardNumber: 'STORY-03',
    title: 'Family Inheritance Dispute',
    description: 'A long-standing conflict over a will or family estate has turned deadly. Recent changes to the inheritance created winners and losers.',
    clueTypes: ['legal_documents', 'correspondence'],
  },
  {
    id: 'SC-004',
    physicalCardNumber: 'STORY-04',
    title: 'Embezzlement Cover-Up',
    description: 'The victim discovered evidence of financial crimes. The perpetrator killed to prevent exposure and prosecution.',
    clueTypes: ['financial_records', 'digital_device', 'business_documents'],
  },
  {
    id: 'SC-005',
    physicalCardNumber: 'STORY-05',
    title: 'Blackmail Gone Wrong',
    description: 'The victim was blackmailing someone over a dark secret. The victim\'s demands became too dangerous to tolerate.',
    clueTypes: ['correspondence', 'photographs', 'digital_device'],
  },
  {
    id: 'SC-006',
    physicalCardNumber: 'STORY-06',
    title: 'Business Partnership Betrayal',
    description: 'A business partnership soured over money, control, or ethics. One partner decided elimination was the only solution.',
    clueTypes: ['business_documents', 'financial_records', 'correspondence'],
  },
  {
    id: 'SC-007',
    physicalCardNumber: 'STORY-07',
    title: 'Witness Elimination',
    description: 'The victim witnessed a crime and became a liability. They were killed to ensure their silence.',
    clueTypes: ['correspondence', 'security_footage', 'phone_records'],
  },
  {
    id: 'SC-008',
    physicalCardNumber: 'STORY-08',
    title: 'Addiction and Debt',
    description: 'Gambling, drugs, or other addiction created desperate financial need. The victim was killed for money or to erase a debt.',
    clueTypes: ['financial_records', 'personal_items', 'correspondence'],
  },
  {
    id: 'SC-009',
    physicalCardNumber: 'STORY-09',
    title: 'Professional Rivalry',
    description: 'Competition for a promotion, client, or professional reputation turned lethal. The victim stood in the killer\'s way.',
    clueTypes: ['business_documents', 'correspondence', 'digital_device'],
  },
  {
    id: 'SC-010',
    physicalCardNumber: 'STORY-10',
    title: 'Revenge for Past Wrong',
    description: 'The killer harbored resentment over a past betrayal, humiliation, or injustice. Years of anger finally erupted.',
    clueTypes: ['correspondence', 'personal_items', 'photographs'],
  },
  {
    id: 'SC-011',
    physicalCardNumber: 'STORY-11',
    title: 'Custody Battle',
    description: 'A bitter custody dispute pushed a desperate parent to the breaking point. The victim threatened to take the children away forever.',
    clueTypes: ['legal_documents', 'correspondence', 'phone_records'],
  },
  {
    id: 'SC-012',
    physicalCardNumber: 'STORY-12',
    title: 'Medical Malpractice Cover-Up',
    description: 'A fatal medical error was about to be exposed. The person responsible killed to bury the evidence and protect their career.',
    clueTypes: ['medical_records', 'correspondence', 'digital_device'],
  },
  {
    id: 'SC-013',
    physicalCardNumber: 'STORY-13',
    title: 'Political Scandal',
    description: 'The victim possessed information that could destroy a political career. The stakes were too high to let the truth come out.',
    clueTypes: ['correspondence', 'digital_device', 'photographs'],
  },
  {
    id: 'SC-014',
    physicalCardNumber: 'STORY-14',
    title: 'Workplace Harassment Revenge',
    description: 'Years of workplace harassment went unreported and unpunished. The victim finally became the target of their own cruelty.',
    clueTypes: ['correspondence', 'digital_device', 'personal_items'],
  },
  {
    id: 'SC-015',
    physicalCardNumber: 'STORY-15',
    title: 'Property Dispute',
    description: 'A contested piece of property worth a fortune became the catalyst for murder. Neither side was willing to walk away.',
    clueTypes: ['legal_documents', 'financial_records', 'correspondence'],
  },
  {
    id: 'SC-016',
    physicalCardNumber: 'STORY-16',
    title: 'Criminal Alliance Breakdown',
    description: 'A criminal partnership fractured when one party wanted out. The other decided that silence was the only guarantee.',
    clueTypes: ['financial_records', 'phone_records', 'security_footage'],
  },
  {
    id: 'SC-017',
    physicalCardNumber: 'STORY-17',
    title: 'Identity Theft',
    description: 'The victim discovered someone had stolen their identity and was living a double life. Confronting the thief proved fatal.',
    clueTypes: ['digital_device', 'financial_records', 'personal_items'],
  },
  {
    id: 'SC-018',
    physicalCardNumber: 'STORY-18',
    title: 'Espionage',
    description: 'Corporate or government secrets were being sold to the highest bidder. The victim got too close to the truth.',
    clueTypes: ['digital_device', 'correspondence', 'security_footage'],
  },
  {
    id: 'SC-019',
    physicalCardNumber: 'STORY-19',
    title: 'Cult Activity',
    description: 'The victim tried to leave a secretive group or expose its practices. The group ensured their silence permanently.',
    clueTypes: ['personal_items', 'correspondence', 'photographs'],
  },
  {
    id: 'SC-020',
    physicalCardNumber: 'STORY-20',
    title: 'Drug Trafficking',
    description: 'A drug operation was threatened by the victim\'s knowledge or interference. The supply chain had to be protected at any cost.',
    clueTypes: ['financial_records', 'phone_records', 'forensic_evidence'],
  },
  {
    id: 'SC-021',
    physicalCardNumber: 'STORY-21',
    title: 'Stalker Obsession',
    description: 'An obsessive fixation escalated from surveillance to violence. The stalker could not accept rejection.',
    clueTypes: ['photographs', 'digital_device', 'personal_items'],
  },
  {
    id: 'SC-022',
    physicalCardNumber: 'STORY-22',
    title: 'Wrongful Termination',
    description: 'Being fired unjustly destroyed someone\'s livelihood and reputation. The former employee returned seeking a different kind of severance.',
    clueTypes: ['business_documents', 'correspondence', 'phone_records'],
  },
  {
    id: 'SC-023',
    physicalCardNumber: 'STORY-23',
    title: 'Secret Identity',
    description: 'The victim was not who they claimed to be. Someone from their past tracked them down and made sure the secret died with them.',
    clueTypes: ['personal_items', 'digital_device', 'photographs'],
  },
  {
    id: 'SC-024',
    physicalCardNumber: 'STORY-24',
    title: 'Stolen Research',
    description: 'Groundbreaking research was stolen and someone profited enormously. The original creator demanded credit and was silenced.',
    clueTypes: ['digital_device', 'business_documents', 'correspondence'],
  },
  {
    id: 'SC-025',
    physicalCardNumber: 'STORY-25',
    title: 'Money Laundering',
    description: 'Dirty money was being cleaned through legitimate businesses. The victim stumbled onto the operation and became a threat.',
    clueTypes: ['financial_records', 'business_documents', 'digital_device'],
  },
  {
    id: 'SC-026',
    physicalCardNumber: 'STORY-26',
    title: 'Contract Killing',
    description: 'Someone hired a professional to eliminate the victim. The trail leads back to the person who placed the order.',
    clueTypes: ['financial_records', 'phone_records', 'security_footage'],
  },
  {
    id: 'SC-027',
    physicalCardNumber: 'STORY-27',
    title: 'Witness Protection Breach',
    description: 'A protected witness\'s location was compromised. Someone inside the system leaked the information that led to the killing.',
    clueTypes: ['legal_documents', 'phone_records', 'correspondence'],
  },
  {
    id: 'SC-028',
    physicalCardNumber: 'STORY-28',
    title: 'Police Corruption',
    description: 'A corrupt officer\'s criminal activities were about to be exposed. The victim was the only one who had the evidence.',
    clueTypes: ['digital_device', 'financial_records', 'security_footage'],
  },
  {
    id: 'SC-029',
    physicalCardNumber: 'STORY-29',
    title: 'Toxic Relationship',
    description: 'A controlling and abusive relationship reached its breaking point. One partner decided escape was impossible without violence.',
    clueTypes: ['personal_items', 'phone_records', 'medical_records'],
  },
  {
    id: 'SC-030',
    physicalCardNumber: 'STORY-30',
    title: 'Child Custody Kidnapping',
    description: 'A parent\'s attempt to flee with their child was intercepted by the victim. The confrontation turned deadly.',
    clueTypes: ['legal_documents', 'phone_records', 'security_footage'],
  },
  {
    id: 'SC-031',
    physicalCardNumber: 'STORY-31',
    title: 'Organ Trafficking',
    description: 'An illegal organ trade ring was operating in plain sight. The victim discovered the operation and had to be eliminated.',
    clueTypes: ['medical_records', 'financial_records', 'forensic_evidence'],
  },
  {
    id: 'SC-032',
    physicalCardNumber: 'STORY-32',
    title: 'Art Forgery',
    description: 'Millions were made selling forged masterpieces. The victim was about to expose the fraud and destroy the forger\'s empire.',
    clueTypes: ['photographs', 'financial_records', 'correspondence'],
  },
  {
    id: 'SC-033',
    physicalCardNumber: 'STORY-33',
    title: 'Gambling Ring',
    description: 'An underground gambling operation generated enormous debts and desperate people. The victim owed too much or knew too much.',
    clueTypes: ['financial_records', 'phone_records', 'personal_items'],
  },
  {
    id: 'SC-034',
    physicalCardNumber: 'STORY-34',
    title: 'Cybercrime',
    description: 'A sophisticated hacking operation was uncovered by the victim. The cybercriminal killed to protect their digital empire.',
    clueTypes: ['digital_device', 'financial_records', 'correspondence'],
  },
  {
    id: 'SC-035',
    physicalCardNumber: 'STORY-35',
    title: 'Environmental Crime Cover-Up',
    description: 'Illegal dumping of toxic waste was poisoning a community. The victim gathered proof and was murdered before going public.',
    clueTypes: ['business_documents', 'photographs', 'forensic_evidence'],
  },
  {
    id: 'SC-036',
    physicalCardNumber: 'STORY-36',
    title: 'Religious Extremism',
    description: 'A zealot believed the victim was a threat to their faith or community. Religious conviction became justification for murder.',
    clueTypes: ['personal_items', 'correspondence', 'digital_device'],
  },
  {
    id: 'SC-037',
    physicalCardNumber: 'STORY-37',
    title: 'Academic Fraud',
    description: 'Fabricated research and plagiarized work built a prestigious career. The victim threatened to bring it all crashing down.',
    clueTypes: ['digital_device', 'business_documents', 'correspondence'],
  },
  {
    id: 'SC-038',
    physicalCardNumber: 'STORY-38',
    title: 'Diplomatic Incident',
    description: 'A diplomatic figure was involved in criminal activity protected by immunity. The victim tried to hold them accountable.',
    clueTypes: ['legal_documents', 'correspondence', 'security_footage'],
  },
  {
    id: 'SC-039',
    physicalCardNumber: 'STORY-39',
    title: 'Human Trafficking',
    description: 'A trafficking network was operating through a legitimate front. The victim discovered the truth and became a target.',
    clueTypes: ['financial_records', 'phone_records', 'photographs'],
  },
  {
    id: 'SC-040',
    physicalCardNumber: 'STORY-40',
    title: 'Poisoning',
    description: 'A slow and deliberate poisoning was designed to look like natural illness. The victim began to suspect and had to be silenced.',
    clueTypes: ['medical_records', 'forensic_evidence', 'personal_items'],
  },
  {
    id: 'SC-041',
    physicalCardNumber: 'STORY-41',
    title: 'Serial Crime',
    description: 'The victim was not the first and may not be the last. A pattern of disappearances points to a calculating predator.',
    clueTypes: ['forensic_evidence', 'photographs', 'personal_items'],
  },
  {
    id: 'SC-042',
    physicalCardNumber: 'STORY-42',
    title: 'Cold Case Reopened',
    description: 'New evidence in an old unsolved crime threatened to expose the original killer. They struck again to keep the past buried.',
    clueTypes: ['forensic_evidence', 'correspondence', 'photographs'],
  },
  {
    id: 'SC-043',
    physicalCardNumber: 'STORY-43',
    title: 'Conspiracy Theory',
    description: 'The victim was investigating a conspiracy that turned out to be real. The conspirators ensured the investigation died with them.',
    clueTypes: ['digital_device', 'correspondence', 'personal_items'],
  },
  {
    id: 'SC-044',
    physicalCardNumber: 'STORY-44',
    title: 'Whistleblower Silencing',
    description: 'A corporate whistleblower was about to go public with damning evidence. The company\'s most powerful figure decided to intervene permanently.',
    clueTypes: ['business_documents', 'digital_device', 'phone_records'],
  },
  {
    id: 'SC-045',
    physicalCardNumber: 'STORY-45',
    title: 'Underground Fight Ring',
    description: 'An illegal fighting operation generated huge profits and ruined lives. The victim threatened to expose the organizers.',
    clueTypes: ['financial_records', 'phone_records', 'security_footage'],
  },
  {
    id: 'SC-046',
    physicalCardNumber: 'STORY-46',
    title: 'Inheritance Manipulation',
    description: 'Someone systematically manipulated an elderly relative to change their will. The victim caught on and confronted the manipulator.',
    clueTypes: ['legal_documents', 'correspondence', 'financial_records'],
  },
  {
    id: 'SC-047',
    physicalCardNumber: 'STORY-47',
    title: 'Real Estate Fraud',
    description: 'Fraudulent property deals bilked investors out of millions. The victim discovered the scheme and demanded their money back.',
    clueTypes: ['financial_records', 'business_documents', 'legal_documents'],
  },
  {
    id: 'SC-048',
    physicalCardNumber: 'STORY-48',
    title: 'Tax Evasion Murder',
    description: 'Years of hidden income and offshore accounts were about to be reported to authorities. The victim knew the numbers and had to be stopped.',
    clueTypes: ['financial_records', 'digital_device', 'business_documents'],
  },
  {
    id: 'SC-049',
    physicalCardNumber: 'STORY-49',
    title: 'Retirement Fund Theft',
    description: 'Someone embezzled from a retirement fund, devastating dozens of families. The victim uncovered the theft and was killed before they could report it.',
    clueTypes: ['financial_records', 'business_documents', 'correspondence'],
  },
  {
    id: 'SC-050',
    physicalCardNumber: 'STORY-50',
    title: 'Domestic Violence Escalation',
    description: 'A pattern of domestic abuse escalated to its most extreme conclusion. The victim\'s attempts to leave triggered a fatal response.',
    clueTypes: ['medical_records', 'phone_records', 'personal_items'],
  },
];

export const CRIME_SCENE_TILES: CrimeSceneTile[] = [
  {
    id: 'tile_study',
    name: 'Study',
    physicalTileNumber: 'TILE-01',
    inspectableAreas: ['desk', 'bookshelf', 'window', 'floor'],
  },
  {
    id: 'tile_kitchen',
    name: 'Kitchen',
    physicalTileNumber: 'TILE-02',
    inspectableAreas: ['counter', 'drawer', 'pantry', 'sink'],
  },
  {
    id: 'tile_master_bedroom',
    name: 'Master Bedroom',
    physicalTileNumber: 'TILE-03',
    inspectableAreas: ['bed', 'nightstand', 'closet', 'dresser'],
  },
  {
    id: 'tile_office',
    name: 'Office',
    physicalTileNumber: 'TILE-04',
    inspectableAreas: ['desk', 'filing_cabinet', 'safe', 'window'],
  },
  {
    id: 'tile_parking_lot',
    name: 'Parking Lot',
    physicalTileNumber: 'TILE-05',
    inspectableAreas: ['entrance', 'camera', 'dumpster', 'vehicle'],
  },
];

export const LAB_TESTS: LabTest[] = [
  {
    id: 'dna_test',
    name: 'DNA Analysis',
    delayMinutes: 8,
    evidenceRequired: ['weapon'],
  },
  {
    id: 'fiber_analysis',
    name: 'Fiber Spectrometry',
    delayMinutes: 5,
    evidenceRequired: ['fiber'],
  },
  {
    id: 'gps_triangulation',
    name: 'GPS Triangulation',
    delayMinutes: 3,
    evidenceRequired: ['phone_records'],
  },
  {
    id: 'financial_audit',
    name: 'Forensic Financial Audit',
    delayMinutes: 10,
    evidenceRequired: ['financial_docs'],
  },
  {
    id: 'footage_enhancement',
    name: 'Digital Footage Enhancement',
    delayMinutes: 6,
    evidenceRequired: ['security_footage'],
  },
];

export const SCENARIOS: Scenario[] = [
  {
    id: 'scenario_1',
    title: 'Small Town Betrayal',
    tagline: 'A prominent businessman is found dead in his study — and everyone in the family had a reason to want him gone.',
    difficulty: 2,
    defaultTimerMinutes: 90,
    playerCount: '1-4',
    tileConfiguration: [
      { tileId: 'tile_study', position: { x: 0, y: 0 }, hasVictim: true, evidenceMarkers: ['weapon', 'fiber'] },
      { tileId: 'tile_master_bedroom', position: { x: 1, y: 0 }, evidenceMarkers: ['phone_records'] },
      { tileId: 'tile_office', position: { x: 0, y: 1 }, evidenceMarkers: ['financial_docs'] },
      { tileId: 'tile_parking_lot', position: { x: 1, y: 1 }, evidenceMarkers: ['security_footage'] },
    ],
    storyCardIds: ['SC-002', 'SC-003'],
    suspectAssignments: [
      { profileId: 'S-001', roleInCase: "Victim's Spouse", motive: 'Financial desperation', relationshipToVictim: 'Married to victim for 12 years', hasAccess: true },
      { profileId: 'S-002', roleInCase: 'Estranged Brother', motive: 'Inheritance dispute', relationshipToVictim: 'Estranged sibling', hasAccess: false },
      { profileId: 'S-003', roleInCase: "Victim's Daughter", motive: 'Cash desperation', relationshipToVictim: 'Daughter', hasAccess: true },
      { profileId: 'S-004', roleInCase: 'Business Partner', motive: 'Embezzlement cover-up', relationshipToVictim: 'Co-founder of Voss & Holt Industries', hasAccess: true },
      { profileId: 'S-005', roleInCase: 'Employee / Witness', relationshipToVictim: 'Long-time assistant', hasAccess: true },
    ],
    sceneInspections: {
      study_desk: {
        areaId: 'study_desk',
        description: 'The victim\'s desk is cluttered with financial papers. A heavy crystal decanter lies shattered nearby, stained with blood.',
        evidenceFound: ['weapon', 'financial_docs'],
      },
      study_bookshelf: {
        areaId: 'study_bookshelf',
        description: 'Several leather-bound books are slightly askew. Behind one, you find a hidden compartment — empty.',
        evidenceFound: [],
      },
      study_floor: {
        areaId: 'study_floor',
        description: 'Microscopic fiber fragments are visible on the victim\'s clothing under UV light.',
        evidenceFound: ['fiber'],
      },
      master_bedroom_nightstand: {
        areaId: 'master_bedroom_nightstand',
        description: 'The victim\'s personal phone rests on the nightstand, still powered on.',
        evidenceFound: ['phone_records'],
      },
      parking_lot_camera: {
        areaId: 'parking_lot_camera',
        description: 'A CCTV camera covers the entrance. The footage is partially corrupted but time-stamped.',
        evidenceFound: ['security_footage'],
      },
    },
    evidenceContent: [
      { typeId: 'weapon', locationFound: 'study_desk', content: 'A heavy crystal decanter recovered near the scene. Blood and possible biological trace on handle.' },
      { typeId: 'fiber', locationFound: 'study_floor', content: 'Microscopic fiber fragments collected from the victim\'s clothing. Unusual weave pattern.' },
      { typeId: 'phone_records', locationFound: 'master_bedroom_nightstand', content: 'Victim\'s call log and GPS data from the night of the incident.' },
      { typeId: 'financial_docs', locationFound: 'study_desk', content: 'Bank statements and wire transfer records flagged by forensic accountant.' },
      { typeId: 'security_footage', locationFound: 'parking_lot_camera', content: 'Partial CCTV capture from the building entrance. Time-stamped but partially corrupted.' },
    ],
    killerId: 'S-001',
    motive: 'Financial desperation',
    forensicResults: {
      dna_test: 'DNA on weapon matches Margaret Voss (S-001). Profile is conclusive — no mixture detected.',
      fiber_analysis: 'Fibers are synthetic blend consistent with mass-market upholstery. Inconclusive.',
      gps_triangulation: 'Phone GPS places victim at home until 11:47 PM. No anomalous third-party pings detected.',
      financial_audit: 'Victim had secretly changed beneficiary of $2.1M life insurance policy — Margaret remains sole beneficiary.',
      footage_enhancement: 'Enhanced footage shows a figure matching Margaret Voss entering the property at 11:32 PM.',
    },
    plantedEvidence: ['financial_docs'],
    forensicAnchor: {
      testId: 'dna_test',
      evidenceId: 'weapon',
      supportsSuspectId: 'S-001',
      strength: 'strong',
    },
  },
  {
    id: 'scenario_2',
    title: 'Blood Inheritance',
    tagline: 'When the will changes, old grudges turn deadly — and the prodigal brother returns just in time.',
    difficulty: 3,
    defaultTimerMinutes: 90,
    playerCount: '1-4',
    tileConfiguration: [
      { tileId: 'tile_study', position: { x: 0, y: 0 }, hasVictim: true, evidenceMarkers: ['weapon'] },
      { tileId: 'tile_master_bedroom', position: { x: 1, y: 0 }, evidenceMarkers: ['fiber'] },
      { tileId: 'tile_office', position: { x: 0, y: 1 }, evidenceMarkers: ['financial_docs'] },
      { tileId: 'tile_parking_lot', position: { x: 1, y: 1 }, evidenceMarkers: ['security_footage', 'phone_records'] },
    ],
    storyCardIds: ['SC-003'],
    suspectAssignments: [
      { profileId: 'S-001', roleInCase: "Victim's Spouse", relationshipToVictim: 'Married to victim', hasAccess: true },
      { profileId: 'S-002', roleInCase: 'Estranged Brother', motive: 'Inheritance dispute', relationshipToVictim: 'Estranged sibling who contested the will', hasAccess: false },
      { profileId: 'S-003', roleInCase: "Victim's Daughter", relationshipToVictim: 'Daughter and new sole heir', hasAccess: true },
      { profileId: 'S-004', roleInCase: 'Business Partner', relationshipToVictim: 'Co-founder of Voss & Holt Industries', hasAccess: true },
      { profileId: 'S-005', roleInCase: 'Employee / Witness', relationshipToVictim: 'Long-time assistant', hasAccess: true },
    ],
    sceneInspections: {
      study_desk: {
        areaId: 'study_desk',
        description: 'The study shows signs of a violent confrontation. Furniture is overturned.',
        evidenceFound: ['weapon'],
      },
      study_floor: {
        areaId: 'study_floor',
        description: 'The victim\'s jacket lies crumpled on the floor with fiber residue.',
        evidenceFound: ['fiber'],
      },
      office_filing_cabinet: {
        areaId: 'office_filing_cabinet',
        description: 'A recently updated will document is filed here, disinheriting David Chen entirely.',
        evidenceFound: ['financial_docs'],
      },
      parking_lot_vehicle: {
        areaId: 'parking_lot_vehicle',
        description: 'GPS data and partial security footage can be recovered from the parking area.',
        evidenceFound: ['phone_records', 'security_footage'],
      },
    },
    evidenceContent: [
      { typeId: 'weapon', locationFound: 'study_desk', content: 'A heavy crystal decanter with degraded biological trace. The weapon was found near the overturned desk.' },
      { typeId: 'fiber', locationFound: 'study_floor', content: 'Rare cashmere blend fibers on the victim\'s jacket. Unusual weave pattern not from local sources.' },
      { typeId: 'phone_records', locationFound: 'parking_lot_vehicle', content: 'Victim\'s GPS shows a late-night drive to an off-grid rural property.' },
      { typeId: 'financial_docs', locationFound: 'office_filing_cabinet', content: 'Recently updated will removing David Chen entirely. Multi-million-dollar estate redirected to daughter.' },
      { typeId: 'security_footage', locationFound: 'parking_lot_vehicle', content: 'Partially corrupted footage from building entrance. Enhancement may reveal more.' },
    ],
    killerId: 'S-002',
    motive: 'Inheritance dispute',
    forensicResults: {
      dna_test: 'DNA profile on weapon is degraded. Cannot produce conclusive match from available sample.',
      fiber_analysis: 'Fiber match identified — rare cashmere blend sourced to a boutique retailer in David Chen\'s city of residence.',
      gps_triangulation: 'Victim\'s GPS shows a drive to an off-grid location at 10:15 PM. Location matches a property owned by David Chen.',
      financial_audit: 'Company accounts are clean. Victim recently updated will to remove David Chen entirely.',
      footage_enhancement: 'Footage enhancement incomplete — file corruption prevents clear identification.',
    },
    plantedEvidence: ['financial_docs'],
    forensicAnchor: {
      testId: 'fiber_analysis',
      evidenceId: 'fiber',
      supportsSuspectId: 'S-002',
      strength: 'strong',
    },
  },
  {
    id: 'scenario_3',
    title: 'The Silent Ledger',
    tagline: 'Embezzlement, shell companies, and a partner with everything to lose — follow the money before time runs out.',
    difficulty: 4,
    defaultTimerMinutes: 75,
    playerCount: '1-4',
    tileConfiguration: [
      { tileId: 'tile_office', position: { x: 0, y: 0 }, hasVictim: true, evidenceMarkers: ['weapon', 'financial_docs'] },
      { tileId: 'tile_parking_lot', position: { x: 1, y: 0 }, evidenceMarkers: ['security_footage', 'phone_records'] },
      { tileId: 'tile_study', position: { x: 0, y: 1 }, evidenceMarkers: ['fiber'] },
    ],
    storyCardIds: ['SC-004'],
    suspectAssignments: [
      { profileId: 'S-001', roleInCase: "Victim's Spouse", relationshipToVictim: 'Married to victim', hasAccess: false },
      { profileId: 'S-002', roleInCase: 'Estranged Brother', relationshipToVictim: 'No recent contact', hasAccess: false },
      { profileId: 'S-003', roleInCase: "Victim's Daughter", relationshipToVictim: 'Daughter', hasAccess: false },
      { profileId: 'S-004', roleInCase: 'Business Partner', motive: 'Embezzlement cover-up', relationshipToVictim: 'Co-founder, 18-year partnership', hasAccess: true },
      { profileId: 'S-005', roleInCase: 'Employee / Witness', relationshipToVictim: 'Long-time assistant at the company', hasAccess: true },
    ],
    sceneInspections: {
      office_desk: {
        areaId: 'office_desk',
        description: 'The victim was found slumped beside the desk. Financial documents are scattered everywhere.',
        evidenceFound: ['weapon', 'financial_docs'],
      },
      office_safe: {
        areaId: 'office_safe',
        description: 'The office safe is open but appears undisturbed. No signs of theft.',
        evidenceFound: [],
      },
      parking_lot_camera: {
        areaId: 'parking_lot_camera',
        description: 'Security cameras in the parking structure captured vehicle movements that evening.',
        evidenceFound: ['security_footage'],
      },
      parking_lot_entrance: {
        areaId: 'parking_lot_entrance',
        description: 'Phone GPS data can be cross-referenced with building access logs.',
        evidenceFound: ['phone_records'],
      },
      study_floor: {
        areaId: 'study_floor',
        description: 'Fibers found on the victim\'s clothing appear consistent with the victim\'s own wardrobe.',
        evidenceFound: ['fiber'],
      },
    },
    evidenceContent: [
      { typeId: 'weapon', locationFound: 'office_desk', content: 'A heavy crystal decanter with mixed DNA — victim dominant, secondary profile insufficient.' },
      { typeId: 'fiber', locationFound: 'study_floor', content: 'Fiber sample consistent with the victim\'s own clothing. No external contributor identified.' },
      { typeId: 'phone_records', locationFound: 'parking_lot_entrance', content: 'Leonard Holt\'s personal phone was GPS-tracked near the scene at 11:05 PM.' },
      { typeId: 'financial_docs', locationFound: 'office_desk', content: '$870,000 in unauthorized transfers traced through shell accounts to a holding entity linked to Leonard Holt.' },
      { typeId: 'security_footage', locationFound: 'parking_lot_camera', content: 'Enhanced footage reveals a vehicle matching Leonard Holt\'s registered BMW at 10:58 PM.' },
    ],
    killerId: 'S-004',
    motive: 'Embezzlement cover-up',
    forensicResults: {
      dna_test: 'DNA on weapon is a mixture — victim\'s profile dominant, secondary profile insufficient for database match.',
      fiber_analysis: 'Fiber sample is consistent with the victim\'s own clothing. No external contributor identified.',
      gps_triangulation: 'Leonard Holt\'s personal phone was GPS-tracked near the scene at 11:05 PM — 22 minutes before emergency call.',
      financial_audit: '$870,000 in unauthorized transfers traced through shell accounts to a holding entity linked to Leonard Holt.',
      footage_enhancement: 'Enhanced footage reveals a vehicle matching Leonard Holt\'s registered BMW parked outside the building at 10:58 PM.',
    },
    plantedEvidence: ['fiber'],
    forensicAnchor: {
      testId: 'financial_audit',
      evidenceId: 'financial_docs',
      supportsSuspectId: 'S-004',
      strength: 'strong',
    },
  },
];
